apiVersion: v1
kind: Secret
metadata:
  name: maildev
  labels:
    app: maildev
type: Opaque
stringData:
  passwords: |-
    # SMTP username to connect to the server
    INCOMING_USERNAME: maildev
    # SMTP password to connect to the server
    INCOMING_PASSWORD: password
    # SMTP relay where mail will be forwarded
    OUTGOING_HOST: smtp.example.com
    # SMTP relay username
    OUTGOING_USER: smtp
    # SMTP relay password
    OUTGOING_PASS: password
    # Set to any positive value to use SMTPS
    OUTGOING_SECURE: 1
    # web ui username
    WEB_USER: maildev
    # web ui password
    WEB_PASS: password