apiVersion: v1
kind: ConfigMap
metadata:
  name: maildev-config
  labels:
    app: maildev
data:
  # set to any value to disable the webapp interface
  DISABLE_WEB: ""
  # url prefix of the webapp
  BASE_PATHNAME: ""
  # should match the path where the rules configmap was mounted
  AUTO_RELAY_RULES: /data/rules.json
