apiVersion: v1
kind: Pod
metadata:
  name: maildev
  labels:
    app: maildev
spec:
  volumes:
    - name: rules
      configMap:
        name: maildev-rules
  containers:
    - name: maildev
      image: agaveplatform/maildev:latest
      imagePullPolicy: Always
      envFrom:
        - secretRef:
            name: maildev
        - configMapRef:
            name: maildev-config
      volumeMounts:
        - name: rules
          mountPath: /data/rules.json
          subPath: rules.json
